version: "2.7"
services:
  mysql:
    image: mysql:8.0-debian
    environment:
      - MYSQL_ROOT_PASSWORD=Hoang2002 
      - MYSQL_DATABASE=zalora_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    expose:
      - "3306"
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      fpmphalcon:
        condition: service_started
      mysql:
        condition: service_healthy
    ports:
      - "8082:80"
  fpmphalcon:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    environment:
      - DB_SOURCE=mysql://root:Hoang2002@tcp(mysql:3306)/zalora_db
    depends_on:
      mysql:
        condition: service_healthy
    