export const supplierss = [
  {
    id: 123,
    name: 'HM Warehouse',
    stock: 30,
  },
  {
    id: 2091,
    name: 'Zalora Malay',
    stock: 39,
  },
  {
    id: 283,
    name: 'The Icon Warehouse',
    stock: 133,
  },
  {
    id: 123,
    name: 'Express',
    stock: 735,
  },
]

export const ProductDataList = [
  {
    id: 1,
    name: 'Versache Summer Sweater',
    brand: 'VERSS',
    sku: 'VER0923SW',
    size: 'XXL',
    // suppliers: supplierss,
    color: 'Green',
    // status: 'Active',
    stock: 1290,
  },
  {
    id: 2,
    name: 'Omwn Winter Sweater',
    brand: 'OWME',
    sku: 'O0923SW',
    size: 'XXL',
    // suppliers: supplierss,
    color: 'Green',
    // status: 'Active',
    stock: 1290,
  },
  {
    id: 3,
    name: 'Local Ocemf',
    brand: 'LOaf',
    sku: 'LOO0923SW',
    size: 'XXL',
    // suppliers: supplierss,
    color: 'Green',
    // status: 'Active',
    stock: 1290,
  },
  {
    id: 4,
    name: 'Zebbe Trouser',
    brand: 'Zebbe',
    sku: 'ZZ0923SW',
    size: 'XXL',
    // suppliers: supplierss,
    color: 'Green',
    // status: 'Active',
    stock: 1290,
  },
  {
    id: 5,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    // suppliers: supplierss,
    color: 'Green',
    // status: 'Active',
    stock: 1290,
  },
]
