export const ProductRows = [
  {
    id: 1,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
  {
    id: 2,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
  {
    id: 3,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
  {
    id: 4,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
  {
    id: 5,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
  {
    id: 6,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
  {
    id: 7,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
  {
    id: 8,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
  {
    id: 9,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
  {
    id: 10,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
  {
    id: 11,
    name: 'HM Winter Sweater',
    brand: 'HM',
    sku: 'HM0923SW',
    size: 'XXL',
    supplier: 'Zalora Warehouse',
    color: 'Green',
    status: 'Enable',
    stock: 1290,
  },
]
